schema_version = "1.0.0"
id = "DA_WAND"
version = "1.0.0"
name = "DAWand"
tagline = "Neural Mesh Segmentation for Parameterization"
maintainer = "Ron Kiehn & Richard Liu <ronki@uchicago.edu>"
type = "add-on"
website = "https://github.com/threedle/DAWand-Blender/"
tags = ["Mesh", "UV"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
files = "Export/import meshes for segmentation"