schema_version = "1.0.0"
id = "DA_WAND"
version = "1.0.0"
name = "DAWand"
tagline = "Neural Mesh Segmentation for Parameterization"
maintainer = "Ron Kiehn & Richard Liu <ronki@uchicago.edu>"
type = "add-on"
website = "https://github.com/threedle/DAWand-Blender/"
tags = ["Mesh", "UV"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
platforms = ["windows-x64", "macos-x64", "macos-arm64", "linux-x86_64"]

wheels = [
    "./wheels/contourpy-1.3.1-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/cycler-0.12.1-py3-none-any.whl",
    "./wheels/filelock-3.16.1-py3-none-any.whl",
    "./wheels/fonttools-4.55.0-cp311-cp311-macosx_10_9_universal2.whl",
    "./wheels/fsspec-2024.10.0-py3-none-any.whl",
    "./wheels/importlib_resources-6.4.5-py3-none-any.whl",
    "./wheels/jinja2-3.1.4-py3-none-any.whl",
    "./wheels/kiwisolver-1.4.7-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/MarkupSafe-3.0.2-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/mpmath-1.3.0-py3-none-any.whl",
    "./wheels/networkx-3.4.2-py3-none-any.whl",
    "./wheels/numpy-2.1.3-cp311-cp311-macosx_14_0_arm64.whl",
    "./wheels/packaging-24.2-py3-none-any.whl",
    "./wheels/pillow-11.0.0-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/pyparsing-3.2.0-py3-none-any.whl",
    "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
    "./wheels/six-1.16.0-py2.py3-none-any.whl",
    "./wheels/sympy-1.12.1-py3-none-any.whl",
    "./wheels/texttable-1.7.0-py2.py3-none-any.whl",
    "./wheels/typing_extensions-4.12.2-py3-none-any.whl",
    "./wheels/threadpoolctl-3.5.0-py3-none-any.whl",
    "./wheels/zipp-3.21.0-py3-none-any.whl",

    "./wheels/joblib-1.4.2-py3-none-any.whl",
    "./wheels/dill-0.3.9-py3-none-any.whl",
    "./wheels/libigl-2.5.1-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/matplotlib-3.9.2-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/potpourri3d-1.1.0-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/robust_laplacian-1.0.0-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/scikit_learn-1.5.2-cp311-cp311-macosx_12_0_arm64.whl",
    "./wheels/scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl",
    "./wheels/torch-2.5.1-cp311-none-macosx_11_0_arm64.whl",
    "./wheels/igraph-0.11.8-cp311-abi3-macosx_11_0_arm64.whl",
]
